baseURL: "https://pieterbakx.github.io" 
title: Pieter Bakx
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: publications/
          weight: 1 
        - name: Working Papers
          url: workingpapers/
          weight: 2
        - name: Reports
          url: reports/
          weight: 3 
        - name: Resume
          url: cvpieterbakx.pdf
          weight: 4


params:
    description: "This website hosts Pieter Bakx's publications, working papers, reports, curriculum vitae, and contact information."
    author: Pieter Bakx
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["publications","workingpapers","reports"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Dr Pieter Bakx
          subtitle: "I am an associate professor affiliated with the Health Economics group at the Erasmus School for Health Policy and Management, Erasmus University Rotterdam in the Netherlands. I study topics related to the financing and organization of health care, most of my research is on long-term care financing."
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Publications
              url: publications/
            - name: Working Papers
              url: workingpapers/
            - name: Reports
              url: reports/
            - name: Resume
              url: cvpieterbakx.pdf
              
    socialIcons:

        - name: Email
          url: mailto:bakx@eshpm.eur.nl
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=xzA4GscAAAAJ
        - name: Linkedin
          url: https://nl.linkedin.com/in/pieterbakx/nl
        - name: Orcid
          url: https://orcid.org/0000-0001-7749-3091

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Pieter Bakx"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2